version: "3"
services:
  db:
    container_name: multi_pgsql
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DOCKER_PORT}:5432"

  flyway:
    container_name: multi_flyway
    image: flyway/flyway:latest-alpine
    command: migrate
    environment:
      FLYWAY_URL: "jdbc:postgresql://db/${DB_NAME}"
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 8 #secs waiting for PostgreSQL
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db

  api:
    container_name: multi_api
    image: leocavalcante/dwoole:dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
      - 9000:9000
    env_file:
      - ./.env
    depends_on:
      - db
